import type { Metadata } from "next";
import StyledGlobal from "./global.styled";
import StyledTheme from "./theme.styled";

export const metadata: Metadata = {
    title: "Crue - Event Management & Staffing Platform",
    description: "Generated by create next app",
    manifest: '/manifest.json'
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

    return (
      <html lang="en">
        <body>
          <StyledTheme>
            <StyledGlobal/>
            {children}
          </StyledTheme>
        </body>
      </html>
    );
  }